# Default Overrides
data_dir: .

# Theming Stuff
theme: jekyll-theme-minimal
title: Compare open_MODEX model results

# Plugins
plugins:
  - jekyll-readme-index
  - jekyll-titles-from-headings

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

